stages:
  - buildenv
  - build

newmono_buildenv:
  image: docker:19.03.12
  stage: buildenv
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/new_env:$CI_COMMIT_SHA -f scripts/newmono.docker .
    - docker push $CI_REGISTRY_IMAGE/new_env:$CI_COMMIT_SHA

newmono_build:
  image: $CI_REGISTRY_IMAGE/new_env:$CI_COMMIT_SHA
  stage: build
  artifacts:
    paths:
      - bin/*.zip
    expire_in: 50days
  script:
    - apt install -y libgtk2.0-cil-dev

    - ./configure.sh
    - make
    - make install

